### ISSUE TITLE
试用接口

### ISSUE THREAD

**Issue by yijian-zy** [MyScript/interactive-ink-additional-examples-android#1]
请问下有识别的测试接口提供一下测试吗

**Comment by MyScriptSupport** [comment]
Dear yijian-zy,

currently, I am not sur to understand your request. Bing Translator gives the following translation: "Do you have an identified test interface to provide a test?"

No, we do not have any test interface for the iink SDK.

Also, please note we recommend you submit any question you may have on our developer forum: https://developer-support.myscript.com/support/discussions/

Best regards,

Olivier

**Comment by yijian-zy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
谢谢啦！~~您的邮件我已经收到，我会尽快给您回复~~！
